apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pokemon-api-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: pokemon-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
